### ISSUE TITLE
how can i generate the categories and tags page content

### ISSUE THREAD

**Issue by jacobzheng** [blackshow/hexo-theme-freemind.386#12] opened 2018-12-11 06:46 UTC
hi , i like your theme very much ,thank you!
but when i use the theme can't generate the categories and tags pages,it's important  for me !
when i use ````hexo new page tags```` and edit the content like 
````
title: tags
type: tags
layout: tags
````
the tags page seems ok 
but the categories page can't show the right menu and has no tag
can you help me ?

**Comment by blackshow** [comment] 2018-12-12 06:01
```
blog
├── _config.yml
├── scaffolds
│   ├── draft.md
│   ├── page.md
│   └── post.md
├── source
│   ├── _drafts
│   ├── _posts
│   ├── about
│   │   └── index.md
│   ├── categories
│   │   └── index.md
│   ├── js
│   │   └── MathJax.js
│   └── tags
│       └── index.md
└── themes
    └── freemind.386
```
add or update blog/source/tags/index.md,content:
```
title: Tags
layout: tags
---
```
add or update blog/source/categories/index.md,content:
```
title: Categories
layout: categories
---
```

**Comment by blackshow** [comment] 2018-12-12 06:02
Duplicate of #5

**Closed as completed by blackshow** 2018-12-12 06:02 UTC
